/** 定义物品类型的枚举类型 **/
var ItemType;
(function (ItemType) {
    ItemType[ItemType["itUndefinedType"] = 0] = "itUndefinedType";
    ItemType[ItemType["itWeapon"] = 1] = "itWeapon";
    ItemType[ItemType["itDress"] = 2] = "itDress";
    ItemType[ItemType["itHelmet"] = 3] = "itHelmet";
    ItemType[ItemType["itNecklace"] = 4] = "itNecklace";
    ItemType[ItemType["itDecoration"] = 5] = "itDecoration";
    ItemType[ItemType["itBracelet"] = 6] = "itBracelet";
    ItemType[ItemType["itRing"] = 7] = "itRing";
    ItemType[ItemType["itGirdle"] = 8] = "itGirdle";
    ItemType[ItemType["itShoes"] = 9] = "itShoes";
    ItemType[ItemType["itEquipDiamond"] = 10] = "itEquipDiamond";
    ItemType[ItemType["itSpecialRing"] = 11] = "itSpecialRing";
    ItemType[ItemType["itSwing"] = 12] = "itSwing";
    ItemType[ItemType["itExtraWeapon"] = 13] = "itExtraWeapon";
    ItemType[ItemType["itExtraDress"] = 14] = "itExtraDress";
    ItemType[ItemType["itShield"] = 15] = "itShield";
    ItemType[ItemType["itProectRune"] = 16] = "itProectRune";
    ItemType[ItemType["itSoulPearl"] = 17] = "itSoulPearl";
    ItemType[ItemType["itDizzyRing"] = 18] = "itDizzyRing";
    ItemType[ItemType["itFashionDress"] = 19] = "itFashionDress";
    ItemType[ItemType["itWeaponExtend"] = 20] = "itWeaponExtend";
    ItemType[ItemType["itSuperWeapon"] = 21] = "itSuperWeapon";
    ItemType[ItemType["itSuperDress"] = 22] = "itSuperDress";
    ItemType[ItemType["itSuperHelmet"] = 23] = "itSuperHelmet";
    ItemType[ItemType["itSuperNecklace"] = 24] = "itSuperNecklace";
    ItemType[ItemType["itSuperBracelet"] = 25] = "itSuperBracelet";
    ItemType[ItemType["itSuperRing"] = 26] = "itSuperRing";
    ItemType[ItemType["itSuperGirdle"] = 27] = "itSuperGirdle";
    ItemType[ItemType["itSuperShoes"] = 28] = "itSuperShoes";
    ItemType[ItemType["itEquipMax"] = 29] = "itEquipMax";
    ItemType[ItemType["itRideEquipArmor"] = 60] = "itRideEquipArmor";
    ItemType[ItemType["itRideEquipRein"] = 61] = "itRideEquipRein";
    ItemType[ItemType["itRideEquipSaddle"] = 62] = "itRideEquipSaddle";
    ItemType[ItemType["itRideEquipShoe"] = 63] = "itRideEquipShoe";
    ItemType[ItemType["itRideEquipMax"] = 64] = "itRideEquipMax";
    ItemType[ItemType["itQuestItem"] = 101] = "itQuestItem";
    ItemType[ItemType["itFunctionItem"] = 102] = "itFunctionItem";
    ItemType[ItemType["itMedicaments"] = 103] = "itMedicaments";
    ItemType[ItemType["itFastMedicaments"] = 104] = "itFastMedicaments";
    ItemType[ItemType["itItemDiamond"] = 105] = "itItemDiamond";
    ItemType[ItemType["itMedicaments2"] = 106] = "itMedicaments2";
    ItemType[ItemType["itExpBox"] = 113] = "itExpBox";
    ItemType[ItemType["itMine"] = 114] = "itMine";
    ItemType[ItemType["itForce"] = 115] = "itForce";
    ItemType[ItemType["itCircleSoul"] = 116] = "itCircleSoul";
    ItemType[ItemType["itDailyUse"] = 117] = "itDailyUse";
    ItemType[ItemType["itSellBox"] = 118] = "itSellBox";
    ItemType[ItemType["itSkillBook"] = 119] = "itSkillBook";
    ItemType[ItemType["itAutoUse"] = 120] = "itAutoUse";
    ItemType[ItemType["itJieBiaoBox"] = 121] = "itJieBiaoBox";
    ItemType[ItemType["itItemTypeCount"] = 122] = "itItemTypeCount";
    ItemType[ItemType["itNormal"] = 200] = "itNormal";
})(ItemType || (ItemType = {}));
;
//# sourceMappingURL=ItemType.js.map