/**
 * Created by Administrator on 2017/1/14.
 */
var RES_DIR = 'res/';
var RES_DIR_DRAGON = RES_DIR + "dragon/";
var RES_DIR_EFF = RES_DIR + "eff/";
var RES_DIR_SKILLEFF = RES_DIR + "skilleff/";
var RES_DIR_CHARACTER = RES_DIR + "character/";
var RES_DIR_SOUND = RES_DIR + "music/";
var RES_DIR_BTN = RES_DIR + "btn/";
var RES_DIR_IMAGES = RES_DIR + "images/";
var RES_DIR_BG = RES_DIR_IMAGES + "bg/";
var RES_DIR_NPC_BODY = RES_DIR_IMAGES + "npc/";
var RES_DIR_TRANSFER = RES_DIR_IMAGES + "transfer/1.png";
var RES_DIR_IMAGES_ITEM = RES_DIR_IMAGES + "item/";
var RES_DIR_WIN_TITTLE = RES_DIR_IMAGES + "winTitle/";
var RES_DIR_SKILL = RES_DIR_IMAGES + "skill/";
var RES_DIR_PET = RES_DIR_IMAGES + "pet/";
var RES_DIR_PET_SKILL = RES_DIR_IMAGES + "petskill/";
var RES_DIR_INSTRUCTION_TITTLE = RES_DIR_IMAGES + "instructionTitle/";
var RES_DIR_MONSTERICON = RES_DIR_IMAGES + "monsterIcon/";
var RES_DIR_BADGE = RES_DIR_IMAGES + "badge/";
var RES_DIR_TOTEMS_ICON = RES_DIR_IMAGES + "totems/icon/";
var RES_DIR_TOTEMS_NAME = RES_DIR_IMAGES + "totems/name/";
var RES_DIR_BUFF_ICON = RES_DIR_IMAGES + "buff/";
var RES_DIR_ROLE_ICON = RES_DIR_IMAGES + "roleIco/";
var RES_DIR_PURGATORY = RES_DIR_IMAGES + "purgatory/";
var RES_DIR_PURGATORY_ICON = RES_DIR_PURGATORY + "icon/";
var RES_DIR_SYSOPEN_ICON = RES_DIR_IMAGES + "sysIcon/icon/";
var RES_DIR_SYSOPEN_NAME = RES_DIR_IMAGES + "sysIcon/name/";
var RES_DIR_PAGEICON = RES_DIR_IMAGES + "pageIcon/";
var RES_DIR_ADVENTURE = RES_DIR_IMAGES + "adventure/";
var RES_DIR_BODY_SHADOW = RES_DIR_IMAGES + "shadow.png";
var RES_DIR_PURGATORY_SHOW = RES_DIR_PURGATORY + "show/";
var RES_DIR_IMAGES_BANNER = RES_DIR_IMAGES + "banner/";
var RES_DIR_IMAGES_BANNE_ACTIVITY = RES_DIR_IMAGES_BANNER + "activity/";
var RES_DIR_FASHIONCOPY = RES_DIR_IMAGES + "fashionCopy/";
var DIR_ATLAS = "resource/image/atlas/";
//# sourceMappingURL=ResDirEnum.js.map